In [45]:
import pandas as pd

# 这个pandas处理数据效果不太好 建议用numpy
thedata = pd.read_excel(io='Data613.xlsx', sheet_name='数据标准化-建模用')
Preddata = pd.read_excel(io='Data613.xlsx', sheet_name='数据标准化-预测用')
import numpy as np

thedata = np.array(thedata)
Preddata = np.array(Preddata)
# 将表的内容 7个数据表 挨个处理

In [46]:
# 这个数据是公共部分 需要转化为数字
Commonhead = thedata[3:, 4:6]
Commonhead

array([['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'g'],
       ['a', 'g'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'g'],
       ['a', 'g'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'h'],
       ['a', 'g'],
       ['a', 'g'],
       ['a', 'g'],
       ['a', 'g'],
       ['a',

In [47]:
# 处理带关键字的
def convert_to_num(dealdata):
    # 取出每一列的唯一值
    unique_value = np.unique(dealdata)
    index = -1
    # 把关键字挨个处理
    for i in unique_value:
        dealdata = np.where(dealdata == f"{i}", index, dealdata)
        index += 1
    return dealdata


# 替换的方法 取出第1列
Commonhead[:, 0] = convert_to_num(Commonhead[:, 0])
Commonhead[:, 1] = convert_to_num(Commonhead[:, 1])
Commonhead

array([[-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 0],
       [-1, 0],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 0],
       [-1, 0],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [

In [48]:
TABLE_ONE = thedata[3:, 6:19]
# 这个地方必须转成字符串  .astype(str)
TABLE_ONE[:, 12] = convert_to_num(TABLE_ONE[:, 12].astype(str))
TABLE_ONE[:, 12]

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '-1', '-1', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '0', '0', '-1', '-1', '-1', '0', '-1', '-1', '-1', '0', '-1',
       '-1', '0', '0', '1', '1', '1', '1', '1', '1', '-1', '1', '1', '-1',
       '1', '1', '-1', '-1', '-1', '-1', '-1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '1', '1',
       '1', '1', '1', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', 

In [49]:
TABLE_ONE = thedata[3:, 6:19]
# 处理掉汉字
TABLE_ONE[:, 12] = convert_to_num(TABLE_ONE[:, 12].astype(str))
TABLE_TWO = thedata[3:, 19:23]

In [50]:
tempXdata = np.column_stack((TABLE_ONE, TABLE_TWO))
tempXdata

array([[nan, nan, 2.2134, ..., -0.42138, 2.33126, 0.0133],
       [nan, nan, 2.2134, ..., -0.42138, 2.33126, 0.0133],
       [nan, nan, 0.72748, ..., -0.42138, 2.33126, 0.0133],
       ...,
       [-0.45089, 0.2917, -0.01548, ..., -0.42138, 0.89677, 0.0133],
       [-0.32033, 0.5073, -0.01548, ..., -0.42138, 0.89677, 0.0133],
       [-0.32033, 0.184, -0.01548, ..., -0.42138, 0.89677, 0.0133]],
      dtype=object)

In [51]:
# 先判断缺失数据的的条件 这个以百分之70为基准
def Del_deletion_data(datavalue, flag):
    # 删除缺失值过多的列
    if flag == 1:
        del_cols = []
        # 先拿到元数据的长度
        baseLength = datavalue.shape[0]
        # 这个 用来保存需要删除的列
        iterLength = datavalue.shape[1]
        for i in range(iterLength):
            temp = []
            temp = np.where(np.isnan(datavalue[:, i].astype(float)) == True)[0].tolist() + temp
            # print(temp)
            # 用集合去重
            c = set(temp)
            # 计算缺失的总行数
            lack_of_rows = len(c)
            if lack_of_rows > 0.3 * baseLength:
                del_cols.append(i)
                # print(datavalue)
        # flag是1则删除列，如果是0则删除行
        final_data = np.delete(datavalue, del_cols, axis=flag)
        # elif flag == 0:
        #     del_raws=[]+temp
    # 删除含有缺失值的行
    elif flag == 0:
        # 筛选出含有缺失值的行，用set去重
        del_raws=set(np.where(np.isnan(datavalue.astype(float)) == True)[0].tolist())
        del_raws=list(del_raws)
        final_data = np.delete(datavalue, del_raws, axis=flag)
    return final_data

In [52]:
# 删除部分的缺失值过多的列
base_Xdata = Del_deletion_data(tempXdata, 1)
base_Xdata

array([[2.2134, -1.07136, 0.11031, ..., -0.42138, 2.33126, 0.0133],
       [2.2134, -1.07136, 0.46461, ..., -0.42138, 2.33126, 0.0133],
       [0.72748, 0.44016, -1.66119, ..., -0.42138, 2.33126, 0.0133],
       ...,
       [-0.01548, -0.16445, 0.28746, ..., -0.42138, 0.89677, 0.0133],
       [-0.01548, -0.16445, 0.37603, ..., -0.42138, 0.89677, 0.0133],
       [-0.01548, -0.16445, 0.55318, ..., -0.42138, 0.89677, 0.0133]],
      dtype=object)

In [53]:
# 将Y取出来，然后取出缺失值过多的列
Original_Ydata = thedata[3:, 23:61]
Original_Ydata

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [54]:
pred_Ydata = Preddata[3:, 23:61]
pred_Ydata

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., -0.56921, -0.17836, -0.46192]], dtype=object)

In [55]:
# 将 数据比较一下:① 必须是两边都有的数据才可以进行预测或者建模，②数据量必须是超过70%
def Record_usable_cols(datavalue):
    # 先拿到元数据的长度
    baseLength = datavalue.shape[0]
    iterLength = datavalue.shape[1]
    # 这个 用来保存需要删除的列
    del_cols = []
    for i in range(iterLength):
        temp = []
        # 根据缺失值，将索引存到列表中
        temp = np.where(np.isnan(datavalue[:, i].astype(float)) == True)[0].tolist() + temp
        # print(temp)
        # 用集合去重
        c = set(temp)
        # 计算缺失的总行数
        lack_of_rows = len(c)
        if (lack_of_rows < 0.3 * baseLength):
            del_cols.append(i)
            # print(datavalue)
    return del_cols

# 将两个数据的能用的列合并
Original_Ydata_usableCols = Record_usable_cols(Original_Ydata)
pred_Ydata_usableCols = Record_usable_cols(pred_Ydata)
final_cols = list(set(Original_Ydata_usableCols + pred_Ydata_usableCols))
# 这个里面的内容可以用来建模与预测
final_cols

[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [56]:
# 取出Y_data 元数据
Y_data = Original_Ydata[:, final_cols[0]]
Y_data
# 将Y的内容排序,然后分成-1，0，1
# Y_data.tolist()
# Y_data.sort()

array([0.8798, -1.29384, -1.36073, -1.2107, -1.28946, -1.29447, -1.29196,
       -1.28571, -1.29196, -1.29321, -1.29009, -1.29071, -1.29196,
       -1.29509, -1.28821, -1.28571, -1.29134, -1.2107, -1.29134,
       -1.28571, -1.21132, -1.2107, -1.28509, -1.29009, -1.29196,
       -1.29822, -1.29572, -1.29509, -1.29447, -1.28884, -1.29196,
       -1.28696, -1.21007, -1.28509, -1.29634, -1.29196, -1.29196,
       -1.29071, -1.29634, -1.28884, -1.2107, -1.2107, 0.83354, -1.29196,
       -1.28634, -1.29697, -1.35448, -1.28571, -1.29447, -1.29196,
       -1.29822, -1.29822, 0.79603, -1.29009, -1.29634, 0.82104, 0.80041,
       -1.29572, -1.3251, -1.29009, -1.29196, 1.1061, -1.29196, -1.29697,
       -1.29822, -1.29447, -1.29196, -1.29634, -1.29572, -1.29634,
       -1.29697, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, -1.22882, -1.29196, -1.2307, -1.29509, -1.29321,
       -1.29447, -1.29196, -1.29196, 0.74602, 0.74664, 0.74664, 0.52097,
       0.74664, 0.74852, 0

In [57]:
# 将数据合并，然后将数据缺失值删除整行，然后拆分开
# 将 Commonhead,base_Xdata,Y_data
temp_data = np.column_stack((Commonhead, base_Xdata, Y_data))
# 删除缺失的行
temp_data = Del_deletion_data(temp_data, 0)
X_data = temp_data[:,:-1]
Y_data = temp_data[:,-1]
Y_data

array([0.8798, -1.29384, -1.36073, -1.2107, -1.28946, -1.29447, -1.29196,
       -1.28571, -1.29196, -1.29321, -1.29009, -1.29071, -1.29196,
       -1.29509, -1.28821, -1.28571, -1.29134, -1.2107, -1.29134,
       -1.28571, -1.21132, -1.2107, -1.28509, -1.29009, -1.29196,
       -1.29822, -1.29572, -1.29509, -1.29447, -1.28884, -1.21007,
       -1.28509, -1.29634, -1.29196, -1.29196, -1.29071, -1.29634,
       -1.28884, -1.2107, -1.2107, 0.83354, -1.29196, -1.28634, -1.29697,
       -1.35448, -1.28571, -1.29447, -1.29196, -1.29822, -1.29822,
       0.79603, -1.29009, -1.29634, 0.80041, -1.29572, -1.3251, -1.29009,
       -1.29196, 1.1061, -1.29196, -1.29697, -1.29822, -1.29447, -1.29196,
       -1.29634, -1.29572, -1.29634, -1.29697, -1.22882, -1.29196,
       -1.2307, -1.29509, -1.29321, -1.29447, -1.29196, -1.29196, 0.74602,
       0.74664, 0.74664, 0.52097, 0.74664, 0.74852, 0.74727, 0.74789,
       0.74602, -1.29509, -1.29572, 0.53409, 0.74727, -1.29509, -1.22945,
       0.74789, -

In [86]:
X_data

array([[-1, 1, 2.2134, ..., -0.42138, 2.33126, 0.0133],
       [-1, 1, 2.2134, ..., -0.42138, 2.33126, 0.0133],
       [-1, 1, 0.72748, ..., -0.42138, 2.33126, 0.0133],
       ...,
       [2, -1, -0.01548, ..., -0.42138, 0.89677, 0.0133],
       [2, -1, -0.01548, ..., -0.42138, 0.89677, 0.0133],
       [2, -1, -0.01548, ..., -0.42138, 0.89677, 0.0133]], dtype=object)

In [58]:
# 检验一下是否将所有的空值删除完毕，这个地方是用来做验证的 返回为空列表则删除成功！
list(set(np.where(np.isnan(temp_data.astype(float)) == True)[0].tolist()))

[]

In [77]:
'''
    import numpy as np
    arr = np.array([2, 1, 3, 5, 2, 44, 11])
    # print('原来顺序：', arr)
    # argsort是用来排序，会将里面内容按照从大到小给出索引，取反就是从小到大了
    order = np.argsort(-arr)
    # 创建一个全零的形状和原数组一样
    recovery_arr = np.zeros_like(arr)
    for idx, num in enumerate(arr):
        recovery_arr[order[idx]] = num
'''
# 更改Y_data的为-1 0 1
def Deal_sorted_Ydata(data):
    # 用来记录原顺序的数组，取反
    order = np.argsort(-data)
    data=sorted(data)
    # sorted返回的是数组类型，这个地方需要转成ndarray
    data=np.array(data)
    # 根据5%为1，中间90%为0，后5%为-1
    data_length=data.shape[0]
    data[0:int(data_length*0.05)]=1
    data[int(data_length*0.05):int(data_length*0.95)]=0
    data[int(data_length*0.95):]=-1
    # 恢复原来的顺序
    recovery_arr = np.zeros_like(data)
    for idx, num in enumerate(data):
        recovery_arr[order[idx]] = num
    return recovery_arr

In [ ]:
'''
    from copy import copy
    Y_data_sec=copy(Y_data)
    Y_data_sec=Deal_sorted_Ydata(Y_data_sec)
    Y_data_sec
'''

In [87]:
Y_data=Deal_sorted_Ydata(Y_data)
Y_data

array([ 1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0., -1.,  0.,  0.,  0., -1.,  0.,  1.,  0.,
        0.,  1.,  0., -1.,  0.,  0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,
        0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,
        0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [106]:
# 切分训练数据和测试数据
from sklearn.model_selection import train_test_split

## 30%测试数据，70%训练数据，stratify=y表示训练数据和测试数据具有相同的类别比例
X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, test_size=0.3)
# 开始训练模型
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# 开始训练模型 采取随机森林测试
# 获取模型  随机森林
Rfc=RandomForestClassifier(max_depth=15)
# 梯度提升树
Gbc=GradientBoostingClassifier(max_depth=15)

In [91]:
'''
  # 训练模型
    Rfc.fit(X_data, Y_data.astype(int).astype(float))
    Gbc.fit(X_data, Y_data.astype(int).astype(float))
    y_1 = Rfc.predict(X_data)
    y_2 = Gbc.predict(X_data)
    # 预测结果，用的 r2_score
    #计算拟合的结果（测试集的）
    y1_score=r2_score(Y_data,y_1)
    y2_score=r2_score(Y_data,y_2)
    print(y1_score)
    print(y2_score)
    直接过拟合，结果为1
'''

1.0
1.0


In [107]:
X_train, X_test, y_train, y_test

(array([[3, -1, -0.01548, ..., -0.42138, -0.89635, 0.0133],
        [3, 2, 1.47044, ..., -0.42138, -0.89635, 0.0133],
        [-1, 2, -1.5014, ..., 1.55866, 0.00021, 0.0133],
        ...,
        [3, 2, -0.01548, ..., -0.42138, -0.89635, 0.0133],
        [-1, 2, -1.5014, ..., -0.42138, 1.79333, 0.0133],
        [-1, -1, -0.01548, ..., -0.42138, 1.34505, 0.0133]], dtype=object),
 array([[-1, -1, -0.01548, ..., -0.42138, 0.89677, 0.0133],
        [-1, -1, -0.01548, ..., 1.55866, 0.89677, 0.0133],
        [3, -1, -0.01548, ..., -0.42138, -0.89635, 0.0133],
        ...,
        [-1, 2, -0.01548, ..., -0.42138, 0.89677, 0.0133],
        [-1, 2, -1.5014, ..., -0.42138, 0.00021, 0.0133],
        [3, 2, 0.72748, ..., -0.42138, -0.89635, 0.0133]], dtype=object),
 array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0., -1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,

In [119]:
# 训练模型
Rfc.fit(X_train, y_train)
Gbc.fit(X_train, y_train)
y_1 = Rfc.predict(X_test)
y_2 = Gbc.predict(X_test)

In [133]:
from sklearn.metrics import accuracy_score
# 预测结果，用的 r2_score 这个不能用r2，会出问题，这个地方使用准确率更好
#计算拟合的结果（测试集的）
y1_score=accuracy_score(y_test,y_1)
y2_score=accuracy_score(y_test,y_2)
print(y1_score)
print(y2_score)

0.9333333333333333
0.9066666666666666


In [127]:
np.array([y_1.tolist(),y_test.tolist()])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [117]:
k=0
for i in range(y_1.shape[0]):
    if y_test[i]==y_1[i]:
        k+=1
k/y_test.shape[0]

0.9333333333333333

In [131]:
r2_score([1,1],[1,2])

0.0