In [557]:
import pandas as pd

# 这个pandas处理数据效果不太好 建议用numpy
thedata = pd.read_excel(io='Data613.xlsx', sheet_name='数据标准化-建模用')
Preddata = pd.read_excel(io='Data613.xlsx', sheet_name='数据标准化-预测用')
import numpy as np

thedata = np.array(thedata)
Preddata = np.array(Preddata)
# 将表的内容 7个数据表 挨个处理

In [558]:
from copy import copy
from math import ceil
# 所有的方法汇总
# 先判断缺失数据的的条件 这个以百分之70为基准
def Del_deletion_data(datavalue, flag):
    # 删除缺失值过多的列
    if flag == 1:
        del_cols = []
        # 先拿到元数据的长度
        baseLength = datavalue.shape[0]
        # 这个 用来保存需要删除的列
        iterLength = datavalue.shape[1]
        for i in range(iterLength):
            temp = []
            temp = np.where(np.isnan(datavalue[:, i].astype(float)) == True)[0].tolist() + temp
            # print(temp)
            # 用集合去重
            c = set(temp)
            # 计算缺失的总行数
            lack_of_rows = len(c)
            if lack_of_rows > 0.3 * baseLength:
                del_cols.append(i)
                # print(datavalue)
        # flag是1则删除列，如果是0则删除行
        final_data = np.delete(datavalue, del_cols, axis=flag)
        # elif flag == 0:
        #     del_raws=[]+temp
        return final_data,del_cols
    # 删除含有缺失值的行
    elif flag == 0:
        # 筛选出含有缺失值的行，用set去重
        del_raws=set(np.where(np.isnan(datavalue.astype(float)) == True)[0].tolist())
        del_raws=list(del_raws)
        final_data = np.delete(datavalue, del_raws, axis=flag)
    return final_data

# 将 数据比较一下:① 必须是两边都有的数据才可以进行预测或者建模，②数据量必须是超过70%
def Record_usable_cols(datavalue):
    # 先拿到元数据的长度
    baseLength = datavalue.shape[0]
    iterLength = datavalue.shape[1]
    # 这个 用来保存需要删除的列
    del_cols = []
    for i in range(iterLength):
        temp = []
        # 根据缺失值，将索引存到列表中
        temp = np.where(np.isnan(datavalue[:, i].astype(float)) == True)[0].tolist() + temp
        # print(temp)
        # 用集合去重
        c = set(temp)
        # 计算缺失的总行数
        lack_of_rows = len(c)
        if (lack_of_rows < 0.3 * baseLength):
            del_cols.append(i)
            # print(datavalue)
    return del_cols

# 将两个数据的能用的列合并 判断两边的数据是否都存在
# Original_Ydata_usableCols = Record_usable_cols(Original_Ydata)
# pred_Ydata_usableCols = Record_usable_cols(pred_Ydata)
# final_cols = list(set(Original_Ydata_usableCols + pred_Ydata_usableCols))
# 这个里面的内容可以用来建模与预测
# final_cols

# 更改Y_data的为-1 0 1
def Deal_sorted_Ydata(data):
    # 用来记录原顺序的数组，取反
    # order = np.argsort(-data)
    sort_data=copy(data)
    sort_data=sorted(sort_data)
    # sorted返回的是数组类型，这个地方需要转成ndarray
    sort_data=np.array(sort_data)
    data_length=sort_data.shape[0]
    # 根据5%为1，中间90%为0，后5%为-1
    # 这个地方要考虑临界条件，当处于临界条件的值，全部分配给两端
    bound_min_value=data[int(ceil(0.05*data_length))]
    bound_max_value=data[int(ceil(0.95*data_length))]
    print('min长度',int(ceil(0.05*data_length)))
    print(bound_min_value,bound_max_value)
    data=np.where(data<=bound_min_value,-1,data)
    print('data-1: ',data)
    data=np.where(data>=bound_max_value,1,data)
    print('data1: ',data)
    data=np.where((data!=1)&(data!=-1),0,data)
    print('data0: ',data)
    # data[0:int(data_length*0.05)]=1
    # data[int(data_length*0.05):int(data_length*0.95)]=0
    # data[int(data_length*0.95):]=-1
    # 恢复原来的顺序
    # recovery_arr = np.zeros_like(data)
    # for idx, num in enumerate(data):
    #     recovery_arr[order[idx]] = num
    return data,bound_min_value,bound_max_value

In [559]:
# 这个数据是公共部分 需要转化为数字
Commonhead = thedata[3:, 4:6]
# 处理带关键字的
def convert_to_num(dealdata):
    # 取出每一列的唯一值
    unique_value = np.unique(dealdata)
    index = -1
    # 把关键字挨个处理
    for i in unique_value:
        dealdata = np.where(dealdata == f"{i}", index, dealdata)
        index += 1
    return dealdata


# 替换的方法 取出第1列
Commonhead[:, 0] = convert_to_num(Commonhead[:, 0])
Commonhead[:, 1] = convert_to_num(Commonhead[:, 1])
Commonhead

array([[-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 0],
       [-1, 0],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 0],
       [-1, 0],
       [-1, 1],
       [-1, 1],
       [-1, 1],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [-1, 0],
       [

In [560]:
# 处理表1和表2
TABLE_ONE = thedata[3:, 6:19]
# 这个地方必须转成字符串  .astype(str)
TABLE_ONE[:, 12] = convert_to_num(TABLE_ONE[:, 12].astype(str))
# 处理掉汉字
TABLE_ONE[:, 12] = convert_to_num(TABLE_ONE[:, 12].astype(str))
TABLE_TWO = thedata[3:, 19:23]

In [561]:
# 合并一下数据
tempXdata = np.column_stack((TABLE_ONE, TABLE_TWO))
tempXdata

array([[nan, nan, 2.2134, ..., -0.42138, 2.33126, 0.0133],
       [nan, nan, 2.2134, ..., -0.42138, 2.33126, 0.0133],
       [nan, nan, 0.72748, ..., -0.42138, 2.33126, 0.0133],
       ...,
       [-0.45089, 0.2917, -0.01548, ..., -0.42138, 0.89677, 0.0133],
       [-0.32033, 0.5073, -0.01548, ..., -0.42138, 0.89677, 0.0133],
       [-0.32033, 0.184, -0.01548, ..., -0.42138, 0.89677, 0.0133]],
      dtype=object)

In [562]:
# 删除部分的缺失值过多的列
temp_data = Del_deletion_data(tempXdata, 1)
base_Xdata = temp_data[0]
# 获取需要删除的列
del_cols = temp_data[1]
base_Xdata,del_cols

(array([[2.2134, -1.07136, 0.11031, ..., -0.42138, 2.33126, 0.0133],
        [2.2134, -1.07136, 0.46461, ..., -0.42138, 2.33126, 0.0133],
        [0.72748, 0.44016, -1.66119, ..., -0.42138, 2.33126, 0.0133],
        ...,
        [-0.01548, -0.16445, 0.28746, ..., -0.42138, 0.89677, 0.0133],
        [-0.01548, -0.16445, 0.37603, ..., -0.42138, 0.89677, 0.0133],
        [-0.01548, -0.16445, 0.55318, ..., -0.42138, 0.89677, 0.0133]],
       dtype=object),
 [0, 1, 3, 5, 6])

In [563]:
# 将Y取出来，然后取出缺失值过多的列
Original_Ydata = thedata[3:, 23:61]
pred_Ydata = Preddata[3:, 23:61]
Original_Ydata,pred_Ydata

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], dtype=object),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., -0.56921, -0.17836, -0.46192]], dtype=object))

In [564]:
# 将两个数据的能用的列合并 判断两边的数据是否都存在
Original_Ydata_usableCols = Record_usable_cols(Original_Ydata)
pred_Ydata_usableCols = Record_usable_cols(pred_Ydata)
# 取出交集
# list(set(a).intersection(b))
final_cols=list(set(Original_Ydata_usableCols).intersection(pred_Ydata_usableCols))
# final_cols = list(set(Original_Ydata_usableCols + pred_Ydata_usableCols))
# 这个里面的内容可以用来建模与预测(可用的列)
final_cols

[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 23]

In [565]:
# 取出Y_data 元数据
Y_data = Original_Ydata[:, final_cols[0]]
Y_data

array([0.8798, -1.29384, -1.36073, -1.2107, -1.28946, -1.29447, -1.29196,
       -1.28571, -1.29196, -1.29321, -1.29009, -1.29071, -1.29196,
       -1.29509, -1.28821, -1.28571, -1.29134, -1.2107, -1.29134,
       -1.28571, -1.21132, -1.2107, -1.28509, -1.29009, -1.29196,
       -1.29822, -1.29572, -1.29509, -1.29447, -1.28884, -1.29196,
       -1.28696, -1.21007, -1.28509, -1.29634, -1.29196, -1.29196,
       -1.29071, -1.29634, -1.28884, -1.2107, -1.2107, 0.83354, -1.29196,
       -1.28634, -1.29697, -1.35448, -1.28571, -1.29447, -1.29196,
       -1.29822, -1.29822, 0.79603, -1.29009, -1.29634, 0.82104, 0.80041,
       -1.29572, -1.3251, -1.29009, -1.29196, 1.1061, -1.29196, -1.29697,
       -1.29822, -1.29447, -1.29196, -1.29634, -1.29572, -1.29634,
       -1.29697, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, -1.22882, -1.29196, -1.2307, -1.29509, -1.29321,
       -1.29447, -1.29196, -1.29196, 0.74602, 0.74664, 0.74664, 0.52097,
       0.74664, 0.74852, 0

In [566]:
temp_data = np.column_stack(( base_Xdata, Y_data))
# 删除缺失的行
temp_data = Del_deletion_data(temp_data, 0)
X_data = temp_data[:,:-1]
Y_data = temp_data[:,-1]
X_data,Y_data

(array([[2.2134, -1.07136, 0.11031, ..., -0.42138, 2.33126, 0.0133],
        [2.2134, -1.07136, 0.46461, ..., -0.42138, 2.33126, 0.0133],
        [0.72748, 0.44016, -1.66119, ..., -0.42138, 2.33126, 0.0133],
        ...,
        [-0.01548, -0.16445, 0.28746, ..., -0.42138, 0.89677, 0.0133],
        [-0.01548, -0.16445, 0.37603, ..., -0.42138, 0.89677, 0.0133],
        [-0.01548, -0.16445, 0.55318, ..., -0.42138, 0.89677, 0.0133]],
       dtype=object),
 array([0.8798, -1.29384, -1.36073, -1.2107, -1.28946, -1.29447, -1.29196,
        -1.28571, -1.29196, -1.29321, -1.29009, -1.29071, -1.29196,
        -1.29509, -1.28821, -1.28571, -1.29134, -1.2107, -1.29134,
        -1.28571, -1.21132, -1.2107, -1.28509, -1.29009, -1.29196,
        -1.29822, -1.29572, -1.29509, -1.29447, -1.28884, -1.21007,
        -1.28509, -1.29634, -1.29196, -1.29196, -1.29071, -1.29634,
        -1.28884, -1.2107, -1.2107, 0.83354, -1.29196, -1.28634, -1.29697,
        -1.35448, -1.28571, -1.29447, -1.29196, -1.2982

In [567]:
temp_data

array([[2.2134, -1.07136, 0.11031, ..., 2.33126, 0.0133, 0.8798],
       [2.2134, -1.07136, 0.46461, ..., 2.33126, 0.0133, -1.29384],
       [0.72748, 0.44016, -1.66119, ..., 2.33126, 0.0133, -1.36073],
       ...,
       [-0.01548, -0.16445, 0.28746, ..., 0.89677, 0.0133, 0.74977],
       [-0.01548, -0.16445, 0.37603, ..., 0.89677, 0.0133, 0.75415],
       [-0.01548, -0.16445, 0.55318, ..., 0.89677, 0.0133, 0.75227]],
      dtype=object)

In [568]:
# 检验一下是否将所有的空值删除完毕，这个地方是用来做验证的 返回为空列表则删除成功！
list(set(np.where(np.isnan(temp_data.astype(float)) == True)[0].tolist()))

[]

In [569]:
# 替换为-1，0，1的分类
temp_data=Deal_sorted_Ydata(Y_data)
Y_data=temp_data[0]
Y_data_boundsMin=temp_data[1]
Y_data_boundsMax=temp_data[2]

min长度 13
-1.29509 0.7679
data-1:  [0.8798 -1.29384 -1 -1.2107 -1.28946 -1.29447 -1.29196 -1.28571 -1.29196
 -1.29321 -1.29009 -1.29071 -1.29196 -1 -1.28821 -1.28571 -1.29134 -1.2107
 -1.29134 -1.28571 -1.21132 -1.2107 -1.28509 -1.29009 -1.29196 -1 -1 -1
 -1.29447 -1.28884 -1.21007 -1.28509 -1 -1.29196 -1.29196 -1.29071 -1
 -1.28884 -1.2107 -1.2107 0.83354 -1.29196 -1.28634 -1 -1 -1.28571
 -1.29447 -1.29196 -1 -1 0.79603 -1.29009 -1 0.80041 -1 -1 -1.29009
 -1.29196 1.1061 -1.29196 -1 -1 -1.29447 -1.29196 -1 -1 -1 -1 -1.22882
 -1.29196 -1.2307 -1 -1.29321 -1.29447 -1.29196 -1.29196 0.74602 0.74664
 0.74664 0.52097 0.74664 0.74852 0.74727 0.74789 0.74602 -1 -1 0.53409
 0.74727 -1 -1.22945 0.74789 -1 -1.29384 -1.2282 -1 -1.23008 0.74852
 -1.22945 -1.23008 -1.29196 0.75227 0.75227 -1 -1.2307 -1.29259 0.74789
 -1.29196 -1.23008 -1.2307 0.74789 -1.23008 -1.29071 0.74852 0.74602
 -1.19319 0.75165 -1 -1 -1.2282 -1.29447 -1.23008 0.74664 0.74727 0.74602
 -1 -1.29384 -1.29321 -1.22445 -1.29384 0.

In [570]:
from numpy import unique
unique(Y_data)

array([-1, 0, 1], dtype=object)

In [571]:
# 切分训练数据和测试数据
from sklearn.model_selection import train_test_split
## 30%测试数据，70%训练数据，stratify=y表示训练数据和测试数据具有相同的类别比例
X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, test_size=0.3, stratify=Y_data)

In [572]:
from sklearn.metrics import accuracy_score
# 开始训练模型
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# 获取模型  随机森林
Rfc=RandomForestClassifier(max_depth=20)
# 梯度提升树
Gbc=GradientBoostingClassifier(max_depth=20)
# 训练模型
Rfc.fit(X_train, y_train.astype(float))
Gbc.fit(X_train, y_train.astype(float))
y_1 = Rfc.predict(X_test)
y_2 = Gbc.predict(X_test)

In [573]:
np.array([y_1,y_2])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,
         0.,  0.,  0., -1.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0., -1.,
         0.,  1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0., -1.,  0.,
        -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [574]:
y_test

array([0, 0, -1, 0, 1, -1, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0,
       -1, 0, 0, 0, 0, -1, -1, 0, 0, -1, 0], dtype=object)

In [575]:
k=0
for i in range(y_1.shape[0]):
    if y_test[i]==y_1[i]:
        k+=1
k/y_test.shape[0]

0.84

In [576]:
# 计算准确率
y1_score=accuracy_score(y_test.astype(float), y_2)
y2_score=accuracy_score(y_test.astype(float), y_2)
print(y1_score)
print(y2_score)

0.7466666666666667
0.7466666666666667


In [577]:
# 获取预测数据
pred_Ydata = Original_Ydata[:, final_cols[0]]
# 将pred_Ydata 替换成-1，0，1的分类
pred_Ydata=np.where(pred_Ydata>=Y_data_boundsMax,1,pred_Ydata)
pred_Ydata=np.where(pred_Ydata<=Y_data_boundsMin,-1,pred_Ydata)
pred_Ydata=np.where((pred_Ydata>Y_data_boundsMin)&(pred_Ydata<Y_data_boundsMax),0,pred_Ydata)
pred_Ydata

C:\Users\king\AppData\Local\Temp\ipykernel_7532\2037761800.py:4: RuntimeWarning: invalid value encountered in greater_equal
  pred_Ydata=np.where(pred_Ydata>=Y_data_boundsMax,1,pred_Ydata)
C:\Users\king\AppData\Local\Temp\ipykernel_7532\2037761800.py:5: RuntimeWarning: invalid value encountered in less_equal
  pred_Ydata=np.where(pred_Ydata<=Y_data_boundsMin,-1,pred_Ydata)
C:\Users\king\AppData\Local\Temp\ipykernel_7532\2037761800.py:6: RuntimeWarning: invalid value encountered in greater
  pred_Ydata=np.where((pred_Ydata>Y_data_boundsMin)&(pred_Ydata<Y_data_boundsMax),0,pred_Ydata)
C:\Users\king\AppData\Local\Temp\ipykernel_7532\2037761800.py:6: RuntimeWarning: invalid value encountered in less
  pred_Ydata=np.where((pred_Ydata>Y_data_boundsMin)&(pred_Ydata<Y_data_boundsMax),0,pred_Ydata)


array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [578]:
# 合并数据
temp_data = np.column_stack(( X_data, Y_data))
# 删除缺失的行
temp_data = Del_deletion_data(temp_data, 0)
# 获取预测数据的X_data，Y_data
X_verify_data = temp_data[:,:-1]
Y_verify_data = temp_data[:,-1]

In [579]:
# 预测数据
y_1 = Rfc.predict(X_verify_data)
y_2 = Gbc.predict(X_verify_data)
# 计算准确率
verify_y1=accuracy_score(Y_verify_data.astype(float), y_1)
verify_y2=accuracy_score(Y_verify_data.astype(float), y_2)
print(verify_y1)
print(verify_y2)


0.9518072289156626
0.9236947791164659
