In [63]:
import pandas as pd
from numpy import unique

from src.OtherTasks.ML.PreDeal_Tools import Del_deletion_data, Record_usable_cols, Deal_sorted_Ydata, convert_to_num,get_final_useablecols, all_ydata, delAndGetCols
import numpy as np
# 这个pandas处理数据效果不太好 建议用numpy
thedata = pd.read_excel(io='Data613.xlsx', sheet_name='数据标准化-建模用')
Preddata = pd.read_excel(io='Data613.xlsx', sheet_name='数据标准化-预测用')

# 获取数据表对象
thedata = np.array(thedata)
Preddata = np.array(Preddata)
# 将表的内容 7个数据表 挨个处理

In [64]:
def get_merge_tabledata(excel_data):
    # 这个数据是公共部分 需要转化为数字
    Commonhead = excel_data[3:, 4:6]
    # 替换的方法 取出第1列
    Commonhead[:, 0] = convert_to_num(Commonhead[:, 0])
    Commonhead[:, 1] = convert_to_num(Commonhead[:, 1])
    # 处理表1和表2
    TABLE_ONE = excel_data[3:, 6:19]
    # 这个地方必须转成字符串   处理掉汉字
    TABLE_ONE[:, 12] = convert_to_num(TABLE_ONE[:, 12].astype(str))
    TABLE_TWO = excel_data[3:, 19:23]
    # 处理表3
    TABLE_THREE = excel_data[3:, 61:66]
    # 这个地方必须转成字符串   处理掉汉字
    TABLE_THREE[:, -1] = convert_to_num(TABLE_THREE[:, -1].astype(str))
    # 处理表4
    TABLE_FOUR = excel_data[3:, 88:101]
    TABLE_FOUR[:, -1] = convert_to_num(TABLE_FOUR[:, -1].astype(str))
    # 处理表5
    TABLE_FIVE = excel_data[3:, 101:107]
    TABLE_FIVE[:, -1] = convert_to_num(TABLE_FIVE[:, -1].astype(str))
    # 处理表6
    TABLE_SIX = excel_data[3:, 131:144]
    TABLE_SIX[:, -1] = convert_to_num(TABLE_SIX[:, -1].astype(str))
    # 处理表7
    TABLE_SEVEN = excel_data[3:, 172:178]
    TABLE_SEVEN[:, -1] = convert_to_num(TABLE_SEVEN[:, -1].astype(str))
    # 合并一下数据
    mergeTwo_data = np.column_stack((Commonhead, TABLE_ONE, TABLE_TWO))
    mergeThree_data = np.column_stack((mergeTwo_data, TABLE_THREE))
    mergeFour_data = np.column_stack(( mergeThree_data, TABLE_FOUR))
    mergeFive_data = np.column_stack((mergeFour_data, TABLE_FIVE))
    mergeSix_data = np.column_stack((mergeFive_data, TABLE_SIX))
    mergeSeven_data = np.column_stack((mergeSix_data, TABLE_SEVEN))
    return mergeTwo_data, mergeThree_data, mergeFour_data, mergeFive_data, mergeSix_data, mergeSeven_data

In [65]:
# # 这个数据是公共部分 需要转化为数字
# Commonhead = thedata[3:, 4:6]
# # 替换的方法 取出第1列
# Commonhead[:, 0] = convert_to_num(Commonhead[:, 0])
# Commonhead[:, 1] = convert_to_num(Commonhead[:, 1])
# Commonhead

In [66]:
# # 处理所有的X_data
# # 处理表1和表2
# TABLE_ONE = thedata[3:, 6:19]
# # 这个地方必须转成字符串   处理掉汉字
# TABLE_ONE[:, 12] = convert_to_num(TABLE_ONE[:, 12].astype(str))
# TABLE_TWO = thedata[3:, 19:23]
# # 处理表3
# TABLE_THREE = thedata[3:, 61:66]
# # 这个地方必须转成字符串   处理掉汉字
# TABLE_THREE[:, -1] = convert_to_num(TABLE_THREE[:, -1].astype(str))
# # 处理表4
# TABLE_FOUR = thedata[3:, 88:101]
# TABLE_FOUR[:, -1] = convert_to_num(TABLE_FOUR[:, -1].astype(str))
# # 处理表5
# TABLE_FIVE = thedata[3:, 101:107]
# TABLE_FIVE[:, -1] = convert_to_num(TABLE_FIVE[:, -1].astype(str))
# # 处理表6
# TABLE_SIX = thedata[3:, 131:144]
# TABLE_SIX[:, -1] = convert_to_num(TABLE_SIX[:, -1].astype(str))
# # 处理表7
# TABLE_SEVEN = thedata[3:, 172:178]
# TABLE_SEVEN[:, -1] = convert_to_num(TABLE_SEVEN[:, -1].astype(str))

In [67]:
# 合并一下数据
# FormerTwo_data = np.column_stack((Commonhead, TABLE_ONE, TABLE_TWO))
# FormerThree_data = np.column_stack((FormerTwo_data, TABLE_THREE))
# FormerFour_data = np.column_stack((FormerThree_data, TABLE_FOUR))
# FormerFive_data = np.column_stack((FormerFour_data, TABLE_FIVE))
# FormerSix_data = np.column_stack((FormerFive_data, TABLE_SIX))
# FormerSeven_data = np.column_stack((FormerSix_data, TABLE_SEVEN))
# FormerTwo_data

In [68]:
# 获取源建模的X数据 传入的对象是获取的excel对象
FormerTwo_data, FormerThree_data, FormerFour_data, FormerFive_data, FormerSix_data, FormerSeven_data = get_merge_tabledata(thedata)
# 获取预测的X数据
Verify_TABLE_TWO, Verify_TABLE_THREE, Verify_TABLE_FOUR, Verify_TABLE_FIVE, Verify_TABLE_SIX, Verify_TABLE_SEVEN = get_merge_tabledata(Preddata)

tempFormerTwo_data = delAndGetCols(FormerTwo_data)
base_Xdata = tempFormerTwo_data[0]
del_cols = tempFormerTwo_data[1]
# 用del_cols删除验证集X不需要的列
Verify_Xdata = np.delete(Verify_TABLE_TWO, del_cols, axis=1)

tempFormerTwo_data

(array([[-1, 1, 2.2134, ..., -0.42138, 2.33126, 0.0133],
        [-1, 1, 2.2134, ..., -0.42138, 2.33126, 0.0133],
        [-1, 1, 0.72748, ..., -0.42138, 2.33126, 0.0133],
        ...,
        [2, -1, -0.01548, ..., -0.42138, 0.89677, 0.0133],
        [2, -1, -0.01548, ..., -0.42138, 0.89677, 0.0133],
        [2, -1, -0.01548, ..., -0.42138, 0.89677, 0.0133]], dtype=object),
 [2, 3, 5, 7, 8])

In [69]:
def get_former_Ydata(excel_data):
    # 处理所有建模的Y_data
    Merge_TableTwoYdata = excel_data[3:, 23:61]
    Merge_TableThreeYdata = excel_data[3:, 66:88]
    # 没有Original_TableFourYdata
    Merge_TableFiveYdata = excel_data[3:, 107:131]
    Merge_TableSixYdata = excel_data[3:, 144:172]
    Merge_TableSevenYdata = excel_data[1:, 178:249]
    return Merge_TableTwoYdata, Merge_TableThreeYdata, Merge_TableFiveYdata, Merge_TableSixYdata, Merge_TableSevenYdata

# 获取源建模的数据Y_data
Original_TableTwoYdata, Original_TableThreeYdata, Original_TableFiveYdata, Original_TableSixYdata, Original_TableSevenYdata=get_former_Ydata(thedata)
# 获取预测数据的Y_data
Predict_TableTwoYdata, Predict_TableThreeYdata, Predict_TableFiveYdata, Predict_TableSixYdata, Predict_TableSevenYdata=get_former_Ydata(Preddata)

In [70]:
# # 处理所有预测的Y_data
# Pred_TableTwoYdata = Preddata[3:, 23:61]
# Pred_TableThreeYdata = Preddata[3:, 66:88]
# # 没有Pred_TableFourYdata
# Pred_TableFiveYdata = Preddata[3:, 107:131]
# Pred_TableSixYdata = Preddata[3:, 144:172]
# Pred_TableSevenYdata = Preddata[1:, 178:249]

In [71]:
# 将Y取出来，然后取出缺失值过多的列

# 获取可用的列
final_cols = get_final_useablecols(Original_TableTwoYdata, Predict_TableTwoYdata)
final_cols

[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 23]

In [72]:
# 获取可以用的Y_data
Original_YdataList, Pred_YdataList = all_ydata(final_cols, Original_TableTwoYdata, Predict_TableTwoYdata)
# todo 到时候遍历这个列表，然后依次计算
# 建模的Y_data
Modeling_Y_data = Original_YdataList[6]
# 预测的Y_data
Pred_Y_data = Pred_YdataList[6]

In [73]:
# 将建模Y_data分类，并且取出边界值
Y_data,Y_data_boundsMin,Y_data_boundsMax=Deal_sorted_Ydata(Modeling_Y_data)

C:\All_Softwares\Develop_Tools\Idea_Project\CodekingPython\src\OtherTasks\ML\PreDeal_Tools.py:92: RuntimeWarning: invalid value encountered in less_equal
  min_data = np.where(data <= bound_min_value)
C:\All_Softwares\Develop_Tools\Idea_Project\CodekingPython\src\OtherTasks\ML\PreDeal_Tools.py:94: RuntimeWarning: invalid value encountered in greater_equal
  max_data = np.where(data >= bound_max_value)
C:\All_Softwares\Develop_Tools\Idea_Project\CodekingPython\src\OtherTasks\ML\PreDeal_Tools.py:96: RuntimeWarning: invalid value encountered in greater
  normal_data = np.where((data > bound_min_value) & (data < bound_max_value))
C:\All_Softwares\Develop_Tools\Idea_Project\CodekingPython\src\OtherTasks\ML\PreDeal_Tools.py:96: RuntimeWarning: invalid value encountered in less
  normal_data = np.where((data > bound_min_value) & (data < bound_max_value))


In [74]:
# 查看是否替换成功
unique(Y_data),Y_data_boundsMin,Y_data_boundsMax

(array([-1, 0, nan, nan, nan, nan, nan, nan, nan, nan, nan, 0, nan, nan,
        nan, 0, nan, 0, 1], dtype=object),
 -0.06839,
 0.62144)

In [75]:
def deal_verify_ydata(Verify_Ydata,Y_data_boundsMin,Y_data_boundsMax):
    # 将pred_Ydata 替换成-1，0，1的分类
    min_data = np.where(Verify_Ydata <= Y_data_boundsMin)
    # print('min_data', min_data)
    max_data = np.where(Verify_Ydata >= Y_data_boundsMax)
    # print('max_data', max_data)
    normal_data = np.where((Verify_Ydata > Y_data_boundsMin) & (Verify_Ydata < Y_data_boundsMax))
    # print('normal_data', normal_data)
    # 统一进行替换为-1，1，0
    Verify_Ydata[min_data] = -1
    Verify_Ydata[max_data] = 1
    Verify_Ydata[normal_data] = 0
    return Verify_Ydata
# 获取预测数据的Y_data
# Verify_Ydata = Pred_Y_data
Verify_Ydata=deal_verify_ydata(Pred_Y_data,Y_data_boundsMin,Y_data_boundsMax)
np.unique(Verify_Ydata)

array([-1, 0, 1], dtype=object)

In [76]:
temp_OriginalXdata = np.column_stack((base_Xdata, Modeling_Y_data))
# 删除缺失的行
temp_OriginalXdata = Del_deletion_data(temp_OriginalXdata, 0)
X_data = temp_OriginalXdata[:, :-1]
Y_data = temp_OriginalXdata[:, -1]
Y_data

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, -1,
       0, -1, 0, -1, -1, 1, 1, 0, 1, 0, 1, 0, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, 0, -1, -1, 0, 0, -1, 0, 0, 0, 1, 0, -1, 0, 0, 0,
       -1, -1, 0, 0, 0, -1, 0, 0, 1, -1, 1, 1, -1, -1, -1, -1, 0, 0, 0, 1,
       0, -1, -1, -1, -1, 1, 0, 0, 0, -1, 0, -1, -1, -1, 0, -1, 0, -1, 0,
       -1, 0, 0, -1, 1, 1, 0, 0, 0, 0, -1, -1, 0, -1, -1, 0, 0, 0, 0, -1,
       -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1,
       -1, -1, -1, 0, 0, 1, 0, 0, -1, -1, 0, 0, -1, -1, -1, -1, 0, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0,
       -1, -1, -1, 0, -1, -1, -1, 0, -1, -1, -1, -1, 0, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, 0, -1, -1, 0, 0, -1, 0, -1, 0, -1, -1, 0, -1,
       0], dtype=object)

In [77]:
# 合并数据
temp_verifydata = np.column_stack((Verify_Xdata, Verify_Ydata))
# 删除缺失的行
temp_verifydata = Del_deletion_data(temp_verifydata, 0)
# 获取预测数据的X_data，Y_data
X_verify_data = temp_verifydata[:, :-1]
Y_verify_data = temp_verifydata[:, -1]

In [78]:
# 检验一下是否将所有的空值删除完毕，这个地方是用来做验证的 返回为空列表则删除成功！
list(set(np.where(np.isnan(temp_OriginalXdata.astype(float)) == True)[0].tolist()))

[]

In [79]:
# 将Y_data分类，并且取出边界值
# Y_data,Y_data_boundsMin,Y_data_boundsMax=Deal_sorted_Ydata(Y_data)

In [80]:
# Y_data_boundsMin,Y_data_boundsMax

In [81]:
# np.where((Y_data > Y_data_boundsMin) & (Y_data < Y_data_boundsMax))[0]
# len(np.where((Y_data > Y_data_boundsMax))[0])+len(np.where((Y_data < Y_data_boundsMin))[0])

In [82]:
# Y_data

In [83]:
# from numpy import unique
# # 查看是否替换成功
# unique(Y_data),Y_data_boundsMin,Y_data_boundsMax

In [84]:
# 切分训练数据和测试数据
from sklearn.model_selection import train_test_split
## 30%测试数据，70%训练数据，stratify=y表示训练数据和测试数据具有相同的类别比例
X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, test_size=0.2, random_state=2)

In [85]:
from sklearn.metrics import accuracy_score
# 开始训练模型
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
# 获取模型  随机森林
Rfc = RandomForestClassifier()
Rfc.fit(X_train, y_train.astype(float))
Rfc_pred = Rfc.predict(X_test)
Rfc_acc= accuracy_score(y_test.astype(float), Rfc_pred)
print('Rfc_acc准确率:', Rfc_acc)

# 梯度提升树
Gbc = GradientBoostingClassifier()
Gbc.fit(X_train, y_train.astype(float))
Gbc_pred = Gbc.predict(X_test)
Gbc_acc=accuracy_score(y_test.astype(float), Gbc_pred)
print('Gbc_acc准确率:',Gbc_acc)

# 使用SVM模型
from sklearn.svm import SVC
Svc = SVC()
Svc.fit(X_train, y_train.astype(float))
Svc_pred = Svc.predict(X_test)
Svc_acc = accuracy_score(y_test.astype(float), Svc_pred)
print('SVC准确率：', Svc_acc)

# 使用KNN模型
from sklearn.neighbors import KNeighborsClassifier
Knc = KNeighborsClassifier()
Knc.fit(X_train, y_train.astype(float))
Knc_pred = Knc.predict(X_test)
Knc_acc = accuracy_score(y_test.astype(float), Knc_pred)
print('KNC准确率：', Knc_acc)

# 使用AdaBoost模型
from sklearn.ensemble import AdaBoostClassifier
Abc = AdaBoostClassifier()
Abc.fit(X_train, y_train.astype(float))
Abc_pred = Abc.predict(X_test)
Abc_acc = accuracy_score(y_test.astype(float), Abc_pred)
print('ABC准确率：', Abc_acc)

# 使用DNN模型
from sklearn.neural_network import MLPClassifier
Dnn = MLPClassifier()
Dnn.fit(X_train, y_train.astype(float))
Dnn_pred = Dnn.predict(X_test)
Dnn_acc = accuracy_score(y_test.astype(float), Dnn_pred)
print('DNN准确率：', Dnn_acc)

# 使用卷积神经网络模型
from sklearn.neural_network import MLPClassifier
CNN = MLPClassifier()
CNN.fit(X_train, y_train.astype(float))
CNN_pred = CNN.predict(X_test)
CNN_acc = accuracy_score(y_test.astype(float), CNN_pred)
print('CNN准确率：', CNN_acc)

# 使用LDA模型
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
Lda = LinearDiscriminantAnalysis()
Lda.fit(X_train, y_train.astype(float))
Lda_pred = Lda.predict(X_test)
Lda_acc = accuracy_score(y_test.astype(float), Lda_pred)
print('LDA准确率：', Lda_acc)

# 使用QDA模型
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
Qda = QuadraticDiscriminantAnalysis()
Qda.fit(X_train, y_train.astype(float))
Qda_pred = Qda.predict(X_test)
Qda_acc = accuracy_score(y_test.astype(float), Qda_pred)
print('QDA准确率：', Qda_acc)


Rfc_acc准确率: 0.62
Gbc_acc准确率: 0.58
SVC准确率： 0.7
KNC准确率： 0.62
ABC准确率： 0.56


C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


DNN准确率： 0.68
CNN准确率： 0.64
LDA准确率： 0.7
QDA准确率： 0.28


C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\discriminant_analysis.py:903: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))
C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\discriminant_analysis.py:903: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))
C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\discriminant_analysis.py:906: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scal

In [86]:
k = 0
for i in range(Rfc_pred.shape[0]):
    if y_test[i] == Rfc_pred[i]:
        k += 1
k / y_test.shape[0]

0.62

In [87]:
# def deal_verify_ydata(Verify_Ydata,Y_data_boundsMin,Y_data_boundsMax):
#     # 将pred_Ydata 替换成-1，0，1的分类
#     min_data = np.where(Verify_Ydata <= Y_data_boundsMin)
#     # print('min_data', min_data)
#     max_data = np.where(Verify_Ydata >= Y_data_boundsMax)
#     # print('max_data', max_data)
#     normal_data = np.where((Verify_Ydata > Y_data_boundsMin) & (Verify_Ydata < Y_data_boundsMax))
#     # print('normal_data', normal_data)
#     # 统一进行替换为-1，1，0
#     Verify_Ydata[min_data] = -1
#     Verify_Ydata[max_data] = 1
#     Verify_Ydata[normal_data] = 0
#     return Verify_Ydata
#
# # 获取预测数据的Y_data
# # Verify_Ydata = Pred_Y_data
# Verify_Ydata=deal_verify_ydata(Pred_Y_data,Y_data_boundsMin,Y_data_boundsMax)
# np.unique(Verify_Ydata)

In [88]:
# # Commonhead
# # 这个数据是公共部分 需要转化为数字
# Commonhead = Preddata[3:, 4:6]
# # 替换的方法 取出第1列
# Commonhead[:, 0] = convert_to_num(Commonhead[:, 0])
# Commonhead[:, 1] = convert_to_num(Commonhead[:, 1])
# # 获取预测数据X_data 处理表1和表2
# Verify_TABLE_ONE = Preddata[3:, 6:19]
# # 这个地方必须转成字符串   处理掉汉字
# Verify_TABLE_ONE[:, 12] = convert_to_num(Verify_TABLE_ONE[:, 12].astype(str))
# Verify_TABLE_TWO = Preddata[3:, 19:23]

In [89]:
# # 获取预测的合并的表
# Verify_TABLE_TWO, Verify_TABLE_THREE, Verify_TABLE_FOUR, Verify_TABLE_FIVE, Verify_TABLE_SIX, Verify_TABLE_SEVEN = get_merge_tabledata(Preddata)
# Verify_Xdata = np.delete(Verify_TABLE_TWO, del_cols, axis=1)

# 获取X_data 临时合并表1和表2，并且删除缺失的列，用之前保存的del_cols
# Verify_Xdata = np.column_stack((Commonhead, Verify_TABLE_ONE, Verify_TABLE_TWO))

In [90]:
# Verify_TABLE_ONE, Verify_TABLE_TWO

In [91]:
# # 合并数据
# temp_data = np.column_stack((Verify_Xdata, Verify_Ydata))
# # 删除缺失的行
# temp_data = Del_deletion_data(temp_data, 0)
# # 获取预测数据的X_data，Y_data
# X_verify_data = temp_data[:, :-1]
# Y_verify_data = temp_data[:, -1]

In [92]:
# np.array([Y_verify_data, Rfc_pred])

In [93]:
# 预测数据
Rfc_pred = Rfc.predict(X_verify_data)
Gbc_pred = Gbc.predict(X_verify_data)
Svc_pred = Svc.predict(X_verify_data)
Knc_pred = Knc.predict(X_verify_data)
Abc_pred = Abc.predict(X_verify_data)
Dnn_pred = Dnn.predict(X_verify_data)
CNN_pred = CNN.predict(X_verify_data)
Lda_pred = Lda.predict(X_verify_data)
Qda_pred = Qda.predict(X_verify_data)
# 计算准确率
verify_y1 = accuracy_score(Y_verify_data.astype(float), Rfc_pred)
verify_y2 = accuracy_score(Y_verify_data.astype(float), Gbc_pred)
verify_y3 = accuracy_score(Y_verify_data.astype(float), Svc_pred)
verify_y4 = accuracy_score(Y_verify_data.astype(float), Knc_pred)
verify_y5 = accuracy_score(Y_verify_data.astype(float), Abc_pred)
verify_y6 = accuracy_score(Y_verify_data.astype(float), Dnn_pred)
verify_y7 = accuracy_score(Y_verify_data.astype(float), CNN_pred)
verify_y8 = accuracy_score(Y_verify_data.astype(float), Lda_pred)
verify_y9 = accuracy_score(Y_verify_data.astype(float), Qda_pred)

print('Gbc', verify_y1)
print('Rfc', verify_y2)
print('Svc', verify_y3)
print('Knc', verify_y4)
print('Abc', verify_y5)
print('Dnn', verify_y6)
print('CNN', verify_y7)
print('Lda', verify_y8)
print('Qda', verify_y9)


C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\discriminant_analysis.py:903: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))


Gbc 0.8011363636363636
Rfc 0.7045454545454546
Svc 0.8068181818181818
Knc 0.6875
Abc 0.11931818181818182
Dnn 0.8011363636363636
CNN 0.7443181818181818
Lda 0.7329545454545454
Qda 0.0625


C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\discriminant_analysis.py:903: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))
C:\All_Softwares\Develop_Tools\Python310\lib\site-packages\sklearn\discriminant_analysis.py:906: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])
