In [1]:
import pandas as pd

# 这个pandas处理数据效果不太好 建议用numpy
thedata = pd.read_excel('5_25Test.xlsx')
import numpy as np

data = thedata.iloc[1:, 2:67]
# 设置列标题
data.columns = thedata.iloc[0, 2:67]
# 将列名全部拿到
col_names = np.array(thedata.iloc[0, 2:67])
data

0   Con-2 Con-3 Con-4 Con-5 Con-6 Con-7 Con-8 Con-9 Con-10 Con-11  ...  Str31  \
1      L1  1055  4300   380    干法     0     0  1500   1200    700  ...   0.07   
2      L1  1055  4300   380    干法     0   0.5  1500   1200    700  ...    NaN   
3      L1  1055  4300   380    干法     0     1  1500   1200    700  ...  0.062   
4      L1  1055  4300   380    干法     0   1.5  1500   1200    700  ...  0.063   
5      L1  1055  4300   380    干法     0     2  1500   1200    700  ...  0.063   
..    ...   ...   ...   ...   ...   ...   ...   ...    ...    ...  ...    ...   
289    L3  1100  8300   NaN    湿法     0   0.5     0   1000    800  ...  0.082   
290    L3  1100  8300   NaN    湿法     0     1     0   1000    800  ...  0.074   
291    L3  1100  8300   NaN    湿法     0   1.5     0   1000    800  ...   0.08   
292    L3  1100  8300   NaN    湿法     0     2     0   1000    800  ...  0.083   
293    L3  1100  8300   NaN    湿法     0     1   500   1000    800  ...  0.073   

0    Str32  Str33  Str34  Str35 Str36  Str37  Str38  Str39  Str40  
1     0.08  0.065  0.068  0.077   0.1   0.07   0.09  0.071   0.08  
2      NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN  
3     0.07  0.072  0.068   0.07  0.08  0.064  0.094  0.068  0.072  
4     0.05  0.071   0.07  0.061  0.07  0.062  0.068  0.076   0.08  
5     0.08   0.07  0.079    0.1   0.1   0.06  0.103  0.097  0.068  
..     ...    ...    ...    ...   ...    ...    ...    ...    ...  
289   0.08   0.09  0.083   0.08  0.05   0.09  0.098  0.116   0.09  
290   0.09   0.09  0.083    0.1  0.05   0.08  0.111   0.09   0.13  
291   0.07   0.08  0.086   0.07   0.1   0.08  0.105  0.092   0.08  
292  0.067   0.07  0.093   0.09  0.11  0.095    0.1   0.11    0.1  
293  0.061   0.08  0.083    0.1  0.05   0.11  0.094   0.08    0.1  

[293 rows x 65 columns]

In [2]:
X_data=np.array(data)
X_data

array([['L1', 1055, 4300, ..., 0.09000000357627869, 0.07100000232458115,
        0.07999999821186066],
       ['L1', 1055, 4300, ..., nan, nan, nan],
       ['L1', 1055, 4300, ..., 0.09399999678134918, 0.06800000369548798,
        0.07199999690055847],
       ...,
       ['L3', 1100, 8300, ..., 0.1049999967217445, 0.09200000017881393,
        0.07999999821186066],
       ['L3', 1100, 8300, ..., 0.1000000014901161, 0.1099999994039536,
        0.1000000014901161],
       ['L3', 1100, 8300, ..., 0.09399999678134918, 0.07999999821186066,
        0.1000000014901161]], dtype=object)

In [3]:
import numpy as np
# 读取Y_data
# 这个pandas处理数据效果不太好 建议用numpy
thedata = pd.read_excel('5_25Test.xlsx')
Y_data=thedata.iloc[1:,67:68]
# 设置列标题
# Y_data.columns=thedata.iloc[0,67:68]
Y_data=np.array(Y_data)
Y_data

array([[184.6999969482422],
       [187.3000030517578],
       [188.6999969482422],
       [188.8000030517578],
       [185],
       [185.3000030517578],
       [186.3000030517578],
       [187.1000061035156],
       [183.8999938964844],
       [187.8999938964844],
       [185.8999938964844],
       [188.3000030517578],
       [187.3000030517578],
       [183.5],
       [187.3000030517578],
       [185.8999938964844],
       [187.3999938964844],
       [178.3000030517578],
       [187.8000030517578],
       [188.1000061035156],
       [187.6000061035156],
       [187.8000030517578],
       [188.5],
       [186.6999969482422],
       [186.6999969482422],
       [187.1000061035156],
       [184.5],
       [188.6000061035156],
       [183.5],
       [185.1000061035156],
       [189.6000061035156],
       [184.3000030517578],
       [189.8000030517578],
       [184.3999938964844],
       [184.6999969482422],
       [183.8000030517578],
       [185.8999938964844],
       [186.6000061035156]

In [4]:
# 处理'/' 将其替换为 空值
X_data[...,2]=np.where(X_data[...,2]=='/',np.nan,X_data[...,2])
# temp=np.where(np.isnan(temp_data[...,2].astype(float))==True)[0]

In [5]:
# 处理带汉字的
def convert_to_num(dealdata):
    # 取出每一列的唯一值
    unique_value=np.unique(dealdata)
    index = -1
    # 把关键字挨个处理
    for i in unique_value:
        dealdata = np.where(dealdata == f"{i}", index, dealdata)
        index += 1
    return dealdata
# 替换的方法 取出第1列
X_data[..., 0]=convert_to_num(X_data[..., 0])
X_data[..., 4]=convert_to_num(X_data[..., 4])

In [6]:
# numpy 新增一列
temp_data=np.column_stack((X_data,Y_data))
temp_data
# 合并列表
# np.c_[X_data,Y_data]
# np.r_[X_data,Y_data]

array([[-1, 1055, 4300, ..., 0.07100000232458115, 0.07999999821186066,
        184.6999969482422],
       [-1, 1055, 4300, ..., nan, nan, 187.3000030517578],
       [-1, 1055, 4300, ..., 0.06800000369548798, 0.07199999690055847,
        188.6999969482422],
       ...,
       [1, 1100, 8300, ..., 0.09200000017881393, 0.07999999821186066,
        nan],
       [1, 1100, 8300, ..., 0.1099999994039536, 0.1000000014901161, nan],
       [1, 1100, 8300, ..., 0.07999999821186066, 0.1000000014901161, nan]],
      dtype=object)

In [ ]:
# todo 删除小于10%的数据  初步分类 0 -1 1

In [265]:
# 处理'/' 将其替换为 空值
temp_data[...,2]=np.where(temp_data[...,2]=='/',np.nan,temp_data[...,2])
# temp=np.where(np.isnan(temp_data[...,2].astype(float))==True)[0]

In [266]:
# 处理带汉字的
def convert_to_num(dealdata):
    # 取出每一列的唯一值
    unique_value=np.unique(dealdata)
    index = -1
    # 把关键字挨个处理
    for i in unique_value:
        dealdata = np.where(dealdata == f"{i}", index, dealdata)
        index += 1
    return dealdata
# 替换的方法 取出第1列
temp_data[..., 0]=convert_to_num(temp_data[..., 0])
temp_data[..., 4]=convert_to_num(temp_data[..., 4])

In [7]:
temp_data

array([[-1, 1055, 4300, ..., 0.07100000232458115, 0.07999999821186066,
        184.6999969482422],
       [-1, 1055, 4300, ..., nan, nan, 187.3000030517578],
       [-1, 1055, 4300, ..., 0.06800000369548798, 0.07199999690055847,
        188.6999969482422],
       ...,
       [1, 1100, 8300, ..., 0.09200000017881393, 0.07999999821186066,
        nan],
       [1, 1100, 8300, ..., 0.1099999994039536, 0.1000000014901161, nan],
       [1, 1100, 8300, ..., 0.07999999821186066, 0.1000000014901161, nan]],
      dtype=object)

In [12]:
# 取出所有为空的索引
temp=[]
for i in range(0,temp_data.shape[1]):
    temp=np.where(np.isnan(temp_data[...,i].astype(float))==True)[0].tolist()+temp
# 用集合去重
c=set(temp)
c=list(c)
c

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 18,
 19,
 20,
 21,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 59,
 60,
 74,
 75,
 80,
 94,
 95,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 148,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 165,
 171,
 181,
 182,
 183,
 184,
 185,
 186,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 216,
 217,
 222,
 224,
 225,
 226,
 227,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 238,
 239,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 2

In [13]:
# 删除具有缺失值的数据  axis=0 是处理行
final_data=np.delete(temp_data,c, axis=0)
final_data

array([[-1, 1055, 4300, ..., 0.0729999989271164, 0.09300000220537186,
        187.8999938964844],
       [-1, 1055, 4300, ..., 0.06100000068545341, 0.09000000357627869,
        185.8999938964844],
       [-1, 1055, 4300, ..., 0.07500000298023224, 0.09300000220537186,
        188.3000030517578],
       ...,
       [1, 1080, 6300, ..., 0.07599999755620956, 0.09000000357627869,
        184.3999938964844],
       [1, 1080, 6300, ..., 0.0729999989271164, 0.07999999821186066,
        182.1000061035156],
       [1, 1080, 6300, ..., 0.07100000232458115, 0.07999999821186066,
        182.8999938964844]], dtype=object)

In [14]:
# 重新获取 X_data Y_data
X_data=final_data[..., [i for i in range(65)]]
Y_data=final_data[...,-1]

In [15]:
# 开始训练模型
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# 开始训练模型 采取随机森林测试
# 获取模型  随机森林
Rfc=RandomForestClassifier()
# 梯度提升树
Gbc=GradientBoostingClassifier()

In [16]:
# 训练模型
Rfc.fit(X_data, Y_data.astype(int).astype(float))
Gbc.fit(X_data, Y_data.astype(int).astype(float))
y_1 = Rfc.predict(X_data)
y_2 = Gbc.predict(X_data)

# 预测结果，用的 r2_score
#计算拟合的结果（测试集的）
y1_score=r2_score(Y_data,y_1)
y2_score=r2_score(Y_data,y_2)

print(y1_score)
print(y2_score)

0.9613155499416399
0.9613155499416399


In [279]:
# 取其他的列 用一个大列表存储进来 然后挨个取出来
import numpy as np
# 读取Y_data
# 这个pandas处理数据效果不太好 建议用numpy
thedata = pd.read_excel('5_25Test.xlsx')

Y_data2=thedata.iloc[1:,68:69]
# 设置列标题
# Y_data.columns=thedata.iloc[0,67:68]
Y_data2=np.array(Y_data2)
Y_data2

array([[0.9358999729156494],
       [0.9412000179290771],
       [0.9430000185966492],
       [0.9487000107765198],
       [0.9309999942779541],
       [0.9323999881744385],
       [0.9383000135421753],
       [0.926800012588501],
       [0.9319999814033508],
       [0.9412000179290771],
       [0.9419999718666077],
       [0.9369999766349792],
       [0.9377999901771545],
       [0.9394000172615051],
       [0.9207000136375427],
       [0.9345999956130981],
       [0.9401000142097473],
       [0.9408000111579895],
       [0.9412000179290771],
       [0.9348999857902527],
       [0.9354000091552734],
       [0.9398999810218811],
       [0.944599986076355],
       [0.9352999925613403],
       [0.9424999952316284],
       [0.9438999891281128],
       [0.9340999722480774],
       [0.9386000037193298],
       [0.9388999938964844],
       [0.9319999814033508],
       [0.9466999769210815],
       [0.9312000274658203],
       [0.9462000131607056],
       [0.9458000063896179],
       [0.947300

In [284]:
# 删除缺失数据
# numpy 新增一列
temp_data=np.column_stack((X_data,Y_data2))
# 取出所有为空的索引
temp = []
for i in range(0, temp_data.shape[1]):
    temp = np.where(np.isnan(temp_data[..., i].astype(float)) == True)[0].tolist() + temp
# 用集合去重
c = set(temp)
c = list(c)
len(c)
# 删除具有缺失值的数据  axis=0 是处理行
final_data2 = np.delete(temp_data, c, axis=0)
final_data2

array([[-1, 1055, 4300, ..., 0.0729999989271164, 0.09300000220537186,
        0.9412000179290771],
       [-1, 1055, 4300, ..., 0.06100000068545341, 0.09000000357627869,
        0.9419999718666077],
       [-1, 1055, 4300, ..., 0.07500000298023224, 0.09300000220537186,
        0.9369999766349792],
       ...,
       [1, 1080, 6300, ..., 0.07599999755620956, 0.09000000357627869,
        0.9343000054359436],
       [1, 1080, 6300, ..., 0.0729999989271164, 0.07999999821186066,
        0.9329000115394592],
       [1, 1080, 6300, ..., 0.07100000232458115, 0.07999999821186066,
        0.9370999932289124]], dtype=object)

In [285]:
# 训练模型
# 重新获取 X_data Y_data
X_data = final_data[..., [i for i in range(65)]]
Y_data = final_data[..., -1]
# 开始训练模型
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# 开始训练模型 采取随机森林测试
# 获取模型  随机森林
Rfc = RandomForestClassifier()
# 梯度提升树
Gbc = GradientBoostingClassifier()
# 训练模型
Rfc.fit(X_data, Y_data.astype(int).astype(float))
Gbc.fit(X_data, Y_data.astype(int).astype(float))
y_1 = Rfc.predict(X_data)
y_2 = Gbc.predict(X_data)

# 预测结果，用的 r2_score
#计算拟合的结果（测试集的）
y1_score = r2_score(Y_data, y_1)
y2_score = r2_score(Y_data, y_2)

print(y1_score)
print(y2_score)

0.9613155499416399
0.9613155499416399


In [ ]:
# ----------------------------------------------------------------------------------------------------

In [ ]:
import numpy as np
# 读取Y_data
# 这个pandas处理数据效果不太好 建议用numpy
thedata = pd.read_excel('5_25Test.xlsx')
Y_data=thedata.iloc[1:,67:68]
# 设置列标题
# Y_data.columns=thedata.iloc[0,67:68]
Y_data=np.array(Y_data)
Y_data

In [ ]:
# 生成一个需要处理的列表的
Deallist=[]
for i in range(len(temp_data)):
    Deallist.append(i)

# 删除带汉字的部分
# Deallist.remove(1)

In [134]:
temp_data.take([3],axis=1)[249]=np.nan
# np.isnan(temp_data.take([3],axis=1)[249].astype(float))

array([nan], dtype=object)

In [78]:
# 取出每一列的唯一值
np.unique(temp_data[...,0])

array(['L1', 'L2', 'L3', 'L4'], dtype=object)

In [81]:
# 取出每一列的唯一值
unique_value=np.unique(temp_data[...,0])
# 替换的方法 取出第1列
c=temp_data[...,0]
index=1
# 把关键字挨个处理
for i in unique_value:
    c=np.where(c==f"{i}",index,c)
    index+=1
c
# np.unique(c)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3], dtype=object)

In [46]:
temp_data[...,-1]
# 取出某几列
# temp_data.take([0,2],axis=1)

array([184.6999969482422, 187.3000030517578, 188.6999969482422,
       188.8000030517578, 185, 185.3000030517578, 186.3000030517578,
       187.1000061035156, 183.8999938964844, 187.8999938964844,
       185.8999938964844, 188.3000030517578, 187.3000030517578, 183.5,
       187.3000030517578, 185.8999938964844, 187.3999938964844,
       178.3000030517578, 187.8000030517578, 188.1000061035156,
       187.6000061035156, 187.8000030517578, 188.5, 186.6999969482422,
       186.6999969482422, 187.1000061035156, 184.5, 188.6000061035156,
       183.5, 185.1000061035156, 189.6000061035156, 184.3000030517578,
       189.8000030517578, 184.3999938964844, 184.6999969482422,
       183.8000030517578, 185.8999938964844, 186.6000061035156,
       186.3000030517578, 187.6000061035156, 189.8999938964844, 186,
       185.3000030517578, 187.5, 187.3999938964844, 185.5,
       205.1999969482422, 192.8000030517578, 188.6000061035156,
       188.3999938964844, 194.6999969482422, 187.6999969482422, 184.5,


In [45]:
temp_data.take([0,2],axis=1)


array([['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1', 4300],
       ['L1',